name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Tests
        uses: docker://python:3.7.4-alpine
        with:
          entrypoint: /bin/sh
          args: -c "python -m unittest discover -v"